service: cleangreenmenu-restapi

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-offline

custom:
  stages:
    - local
    - development
    - staging
    - qa
    - production

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'local'}
  environment: ${file(env/${self:provider.stage}.yml)}
  vpc:
    securityGroupIds:
      - sg-0594f0e78619424b3
    subnetIds:
      - subnet-c89e10e6
      - subnet-e54b0eea

functions:
  createaccount:
    handler: functions/account/create.create
    events:
      - http:
          path: account
          method: post
          cors: true

  login:
    handler: functions/account/login.login
    events:
      - http:
          path: account/login
          method: post
          cors: true

  authorizeuser:
    handler: functions/account/verifytoken.verifytoken

  createrestaurant:
    handler: functions/restaurant/create.create
    events:
      - http:
          path: restaurant
          method: post
          cors: true
          authorizer: authorizeuser

  listrestaurant:
    handler: functions/restaurant/list.list
    events:
      - http:
          path: restaurant
          method: get
          cors: true

  getrestuarant:
    handler: functions/restaurant/get.get
    events:
      - http:
          path: restaurant/{id}
          method: get
          cors: true

  deleterestaurant:
    handler: functions/restaurant/delete.delete
    events:
      - http:
          path: restaurant/{id}
          method: delete
          cors: true
          authorizer: authorizeuser

  createmenu:
    handler: functions/menu/create.create
    events:
      - http:
          path: restaurant/{id}/menu
          method: post
          cors: true
          authorizer: authorizeuser

  getmenu:
    handler: functions/menu/get.get
    events:
      - http:
          path: restaurant/{id}/menu
          method: get
          cors: true

  deletemenu:
    handler: functions/menu/delete.delete
    events:
      - http:
          path: restaurant/{id}/menu/{menuid}
          method: delete
          cors: true
          authorizer: authorizeuser
